spring:
  jpa:
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:marketdb}
#        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: ${DB_CONNECTION:jdbc:mysql://222.122.203.214:3306/marketdb?&characterEncoding=UTF-8&serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:marketdbadmin}
    password: ${DB_PASSWORD:rkawkRkd1!}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
